/**
 * Module for formatting files
 */

const fs = require('fs');

/**
 * Format log files generated by winston to be valid JSON files.
 * It adds trailing comma at end of every line except the last one + encapsulate the whole content into brackets
 * @param {*} file input file path
 */
function formatLogToValidJSON(file) {
    const content = fs.readFileSync(file).toString();
    const arrayContent = content.split("\r\n").filter(element => element);  // apply a filter that removes empty elements
    const arrayContentJSON = arrayContent.map((value) => JSON.parse(value));
    return arrayContentJSON;
}

module.exports.formatLogToValidJSON = formatLogToValidJSON;